#Requires -Version 2.0
<#
.SYNOPSIS
Inventories this Windows Server locally and writes an XLSX workbook to C:\Temp.
.DESCRIPTION
Run elevated under the local or domain administrator account for this server.
This self-contained file does not enumerate AD computers, use WinRM, install
modules, or connect to GitHub. Windows PowerShell 2.0 and later are supported
by the legacy basic collector; the modern collector requires PowerShell 4.0
and Windows Server 2012 or later. Unsupported sections are diagnosed.
.EXAMPLE
.\Invoke-StandaloneServerDiscovery.ps1
.EXAMPLE
.\Invoke-StandaloneServerDiscovery.ps1 -OutputDirectory D:\Discovery
#>
[CmdletBinding()]
param(
    [string]$OutputDirectory='C:\Temp',
    [switch]$IncludeMicrosoftTasks,
    [switch]$UseLegacyCollector
)

# Generated by Standalone/Build-StandaloneServerDiscovery.ps1. Edit its sources.

function New-LocalDiscoveryRow {
    param([hashtable]$Values)
    New-Object PSObject -Property $Values
}

function Add-LocalDiscoveryDiagnostic {
    param([string]$Collector,[string]$Status,[string]$Message,[int]$Count=0)
    $script:LocalDiagnostics.Add((New-LocalDiscoveryRow @{
        Time=Get-Date; ComputerName=$env:COMPUTERNAME; Collector=$Collector
        Status=$Status; RecordCount=$Count; Message=$Message
    }))
}

function Invoke-LocalDiscoverySection {
    param([string]$Name,[scriptblock]$Action)
    Write-Host ('Collecting {0}...' -f $Name)
    # Retain rows already received if a later record in the section fails.
    $records=New-Object 'System.Collections.Generic.List[object]'
    try {
        & $Action | ForEach-Object {if($null -ne $_){$records.Add($_)}}
        Add-LocalDiscoveryDiagnostic $Name Success 'Local collector completed.' $records.Count
    } catch {
        Add-LocalDiscoveryDiagnostic $Name Failed $_.Exception.Message $records.Count
        Write-Warning ('{0}: {1}' -f $Name,$_.Exception.Message)
    }
    Write-Output -NoEnumerate $records.ToArray()
}

function Join-LocalDiscoveryValue {
    param([object[]]$Values,[string]$Separator='; ')
    (@($Values | Where-Object {$null -ne $_ -and ([string]$_).Trim()} |
        ForEach-Object {([string]$_).Trim()} | Sort-Object -Unique) -join $Separator)
}

function Convert-LocalDiscoveryDate {
    param($Value)
    if($Value -is [datetime]){return $Value}
    if($Value){try{[Management.ManagementDateTimeConverter]::ToDateTime([string]$Value)}catch{$null}}
}

function Get-LocalBasicDiscoveryData {
    param([bool]$IncludeMicrosoftTasks=$false)
    $ErrorActionPreference='Stop'
    $ComputerName=$env:COMPUTERNAME
    $script:LocalDiagnostics=New-Object 'System.Collections.Generic.List[object]'
    # No -ComputerName or -Credential: all WMI calls execute on this server.
    $system=Invoke-LocalDiscoverySection 'System' {
        $cs=Get-WmiObject Win32_ComputerSystem
        $os=Get-WmiObject Win32_OperatingSystem
        $cpu=@(Get-WmiObject Win32_Processor)
        $bios=Get-WmiObject Win32_BIOS
        $virtual=$cs.Manufacturer -match 'VMware|QEMU|Xen|innotek' -or $cs.Model -match 'Virtual Machine|VirtualBox|KVM|HVM domU|VMware|Bochs|Xen'
        New-LocalDiscoveryRow @{
            ComputerName=$ComputerName; Domain=$cs.Domain; Manufacturer=$cs.Manufacturer
            Model=$cs.Model; SerialNumber=$bios.SerialNumber
            PhysicalOrVirtual=$(if($virtual){'Virtual'}else{'Physical'})
            OperatingSystem=$os.Caption; Version=$os.Version; Build=$os.BuildNumber
            LastBoot=(Convert-LocalDiscoveryDate $os.LastBootUpTime)
            CPU=(Join-LocalDiscoveryValue @($cpu | ForEach-Object {$_.Name}))
            Sockets=$cpu.Count; Cores=($cpu | Measure-Object NumberOfCores -Sum).Sum
            LogicalProcessors=($cpu | Measure-Object NumberOfLogicalProcessors -Sum).Sum
            MemoryGB=[math]::Round($cs.TotalPhysicalMemory/1GB,2)
        }
    }
    $network=Invoke-LocalDiscoverySection 'Network' {
        foreach($adapter in @(Get-WmiObject Win32_NetworkAdapterConfiguration -Filter 'IPEnabled=True')){
            $addresses=@($adapter.IPAddress)
            for($i=0;$i -lt $addresses.Count;$i++){
                if([string]$addresses[$i] -notmatch '^\d{1,3}(\.\d{1,3}){3}$'){continue}
                $mask=$null; $prefix=$null
                if(@($adapter.IPSubnet).Count -gt $i){$mask=@($adapter.IPSubnet)[$i]}
                if($mask -match '^\d{1,3}(\.\d{1,3}){3}$'){
                    $bits=($mask.Split('.') | ForEach-Object {[Convert]::ToString([int]$_,2).PadLeft(8,'0')}) -join ''
                    if($bits -match '^1*0*$'){$prefix=($bits -replace '0','').Length}
                }
                New-LocalDiscoveryRow @{
                    ComputerName=$ComputerName; Interface=$adapter.Description; IPAddress=$addresses[$i]
                    PrefixLength=$prefix; SubnetMask=$mask
                    Gateway=(Join-LocalDiscoveryValue @($adapter.DefaultIPGateway))
                    DNS=(Join-LocalDiscoveryValue @($adapter.DNSServerSearchOrder)); MacAddress=$adapter.MACAddress
                }
            }
        }
    }
    $storage=Invoke-LocalDiscoverySection 'Storage' {
        Get-WmiObject Win32_LogicalDisk -Filter 'DriveType=3' | Sort-Object DeviceID | ForEach-Object {
            New-LocalDiscoveryRow @{
                ComputerName=$ComputerName; Drive=$_.DeviceID; Label=$_.VolumeName; FileSystem=$_.FileSystem
                SizeGB=[math]::Round($_.Size/1GB,2); FreeGB=[math]::Round($_.FreeSpace/1GB,2)
                PercentFree=$(if($_.Size){[math]::Round(100*$_.FreeSpace/$_.Size,2)}else{$null})
            }
        }
    }
    $roles=Invoke-LocalDiscoverySection 'Roles and Features' {
        Get-WmiObject Win32_ServerFeature | Sort-Object Name | ForEach-Object {
            New-LocalDiscoveryRow @{ComputerName=$ComputerName; Name=$_.Name; DisplayName=$_.Name; FeatureType='Legacy server feature'}
        }
    }
    $applications=Invoke-LocalDiscoverySection 'Applications' {
        # Local registry reads avoid the slow per-property remote registry queries.
        foreach($path in 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall','HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall'){
            if(-not(Test-Path $path)){continue}
            foreach($key in Get-ChildItem $path){
                try{
                    $app=Get-ItemProperty $key.PSPath
                    if(-not $app.DisplayName -or $app.SystemComponent -eq 1){continue}
                    New-LocalDiscoveryRow @{
                        ComputerName=$ComputerName; Name=$app.DisplayName; Version=$app.DisplayVersion
                        Publisher=$app.Publisher; InstallDate=$app.InstallDate; InstallLocation=$app.InstallLocation
                    }
                }catch{Add-LocalDiscoveryDiagnostic 'Applications' Warning ('{0}: {1}' -f $key.PSChildName,$_.Exception.Message)}
            }
        }
    }
    $services=Invoke-LocalDiscoverySection 'Services' {
        Get-WmiObject Win32_Service | Sort-Object DisplayName | ForEach-Object {
            New-LocalDiscoveryRow @{
                ComputerName=$ComputerName; Name=$_.Name; DisplayName=$_.DisplayName; State=$_.State
                StartMode=$_.StartMode; StartName=$_.StartName; PathName=$_.PathName
            }
        }
    }
    $isSql=@($services | Where-Object {$_.Name -match '^(MSSQLSERVER|MSSQL\$|SQLSERVERAGENT|SQLAgent\$|MSOLAP\$|MSSQLServerOLAPService|ReportServer)'}).Count -gt 0
    $isExchange=@($services | Where-Object {$_.Name -match '^MSExchange'}).Count -gt 0
    $class=if($isSql -and $isExchange){'SQL and Exchange'}elseif($isSql){'SQL Server'}elseif($isExchange){'Exchange Server'}else{'General Server'}
    $hasAd=@($services | Where-Object {$_.Name -eq 'NTDS'}).Count -gt 0
    $hasDns=@($services | Where-Object {$_.Name -eq 'DNS'}).Count -gt 0
    $hasDhcp=@($services | Where-Object {$_.Name -eq 'DHCPServer'}).Count -gt 0
    # Local domain-role check prevents domain users being presented as local accounts.
    $isDc=$hasAd
    try{$isDc=[int](Get-WmiObject Win32_ComputerSystem).DomainRole -ge 4}
    catch{Add-LocalDiscoveryDiagnostic 'Domain Role' Warning 'Unable to determine domain-controller status; local account collection will be skipped.'; $isDc=$true}
    foreach($row in $system){
        $row | Add-Member NoteProperty ServerClass $class -Force
        $row | Add-Member NoteProperty CollectionMode 'Local legacy basic only' -Force
    }
    $ports=Invoke-LocalDiscoverySection 'Listening Ports' {
        # TCP listeners have an unspecified foreign endpoint; no localized state-name test.
        $lines=@(& "$env:SystemRoot\System32\netstat.exe" -ano -p tcp)
        if($LASTEXITCODE -ne 0){throw ('netstat exited with code {0}' -f $LASTEXITCODE)}
        foreach($line in $lines){
            $fields=@(($line.Trim() -split '\s+'))
            if($fields.Count -lt 5 -or $fields[0] -ne 'TCP' -or $fields[2] -notmatch '^(0\.0\.0\.0|\[::\]):0$'){continue}
            if($fields[1] -notmatch '^(.*):(\d+)$'){continue}
            $address=$matches[1].Trim('[',']'); $port=[int]$matches[2]; $processId=[int]$fields[-1]
            $processName=$null
            try{$processName=(Get-Process -Id $processId -ErrorAction Stop).ProcessName}catch{}
            New-LocalDiscoveryRow @{ComputerName=$ComputerName; LocalAddress=$address; LocalPort=$port; ProcessId=$processId; ProcessName=$processName}
        }
    }
    $shares=Invoke-LocalDiscoverySection 'Shares and Permissions' {
        foreach($share in Get-WmiObject Win32_Share){
            $sharePermissions=@(); $ntfsPermissions=@()
            try{
                $security=Get-WmiObject Win32_LogicalShareSecuritySetting | Where-Object {$_.Name -eq $share.Name} | Select-Object -First 1
                if(-not $security){throw 'Share security descriptor is unavailable.'}
                $descriptor=$security.GetSecurityDescriptor()
                if($descriptor.ReturnValue -ne 0){throw ('GetSecurityDescriptor returned {0}' -f $descriptor.ReturnValue)}
                foreach($ace in @($descriptor.Descriptor.DACL)){
                    $identity=$ace.Trustee.SIDString
                    if($ace.Trustee.Name){$identity=('{0}\{1}' -f $ace.Trustee.Domain,$ace.Trustee.Name).TrimStart('\')}
                    $rights=[string][Security.AccessControl.FileSystemRights]$ace.AccessMask
                    $kind=if($ace.AceType -eq 0){'Allow'}elseif($ace.AceType -eq 1){'Deny'}else{'ACE type '+$ace.AceType}
                    $sharePermissions+=@('{0}: {1} ({2})' -f $identity,$rights,$kind)
                }
                if($null -eq $descriptor.Descriptor.DACL){$sharePermissions=@('Null DACL (unrestricted)')}
            }catch{Add-LocalDiscoveryDiagnostic 'Shares and Permissions' Warning ('Share {0}: {1}' -f $share.Name,$_.Exception.Message)}
            try{
                if($share.Path -and (Test-Path -LiteralPath $share.Path)){
                    $ntfsPermissions=@((Get-Acl -LiteralPath $share.Path).Access | ForEach-Object {'{0}: {1} ({2})' -f $_.IdentityReference,$_.FileSystemRights,$_.AccessControlType})
                }
            }catch{Add-LocalDiscoveryDiagnostic 'Shares and Permissions' Warning ('NTFS {0}: {1}' -f $share.Name,$_.Exception.Message)}
            New-LocalDiscoveryRow @{
                ComputerName=$ComputerName; Name=$share.Name; Path=$share.Path; UNCPath=('\\{0}\{1}' -f $ComputerName,$share.Name)
                Description=$share.Description; Special=([int64]$share.Type -ge 2147483648)
                SharePermissions=(Join-LocalDiscoveryValue $sharePermissions); NTFSPermissions=(Join-LocalDiscoveryValue $ntfsPermissions)
            }
        }
    }
    $tasks=Invoke-LocalDiscoverySection 'Scheduled Tasks' {
        $scheduler=New-Object -ComObject 'Schedule.Service'
        $scheduler.Connect()
        $folders=New-Object 'System.Collections.Generic.Queue[object]'
        $folders.Enqueue($scheduler.GetFolder('\'))
        while($folders.Count -gt 0){
            $folder=$folders.Dequeue()
            try{
                foreach($child in $folder.GetFolders(0)){
                    if(-not $IncludeMicrosoftTasks -and ($child.Path -eq '\Microsoft' -or $child.Path -like '\Microsoft\*')){continue}
                    $folders.Enqueue($child)
                }
                foreach($task in $folder.GetTasks(1)){
                    $definition=$task.Definition
                    $actions=@($definition.Actions | ForEach-Object {
                        if($_.Type -eq 0){('{0} {1}' -f $_.Path,$_.Arguments).Trim()}else{'Task action type '+$_.Type}
                    })
                    $stateNames=@('Unknown','Disabled','Queued','Ready','Running')
                    $state=[string]$task.State
                    if([int]$task.State -ge 0 -and [int]$task.State -lt $stateNames.Count){$state=$stateNames[[int]$task.State]}
                    New-LocalDiscoveryRow @{
                        ComputerName=$ComputerName; Name=$task.Name; TaskPath=$folder.Path; Executable=(Join-LocalDiscoveryValue $actions)
                        State=$state; RunAsUser=$definition.Principal.UserId; Description=$definition.RegistrationInfo.Description
                    }
                }
            }catch{Add-LocalDiscoveryDiagnostic 'Scheduled Tasks' Warning ('{0}: {1}' -f $folder.Path,$_.Exception.Message)}
        }
    }
    $accounts=@(); $membership=@()
    if($isDc){
        Add-LocalDiscoveryDiagnostic 'Local Accounts' Skipped 'Local accounts are not collected on a domain controller or when its role is unknown.'
        Add-LocalDiscoveryDiagnostic 'Local Group Membership' Skipped 'Local groups are not collected on a domain controller or when its role is unknown.'
    }else{
        $accounts=Invoke-LocalDiscoverySection 'Local Accounts' {
            Get-WmiObject Win32_UserAccount -Filter 'LocalAccount=True' | ForEach-Object {
                New-LocalDiscoveryRow @{ComputerName=$ComputerName; Name=$_.Name; Enabled=(-not $_.Disabled); Description=$_.Description; LastLogon=$null; PasswordExpires=$_.PasswordExpires}
            }
            Add-LocalDiscoveryDiagnostic 'Local Accounts' Warning 'Win32_UserAccount does not expose LastLogon; that field is blank.'
        }
        $membership=Invoke-LocalDiscoverySection 'Local Group Membership' {
            $computer=[ADSI]('WinNT://{0},computer' -f $ComputerName)
            foreach($group in @($computer.psbase.Children | Where-Object {$_.SchemaClassName -eq 'group'})){
                $groupName=[string]$group.Name
                try{
                    foreach($member in @($group.psbase.Invoke('Members'))){
                        $memberType=$member.GetType()
                        $path=$memberType.InvokeMember('AdsPath','GetProperty',$null,$member,$null)
                        $kind=$memberType.InvokeMember('Class','GetProperty',$null,$member,$null)
                        New-LocalDiscoveryRow @{ComputerName=$ComputerName; Group=$groupName; Name=($path -replace '^WinNT://','' -replace '/','\'); ObjectClass=$kind; PrincipalSource='WinNT'}
                    }
                }catch{Add-LocalDiscoveryDiagnostic 'Local Group Membership' Warning ('{0}: {1}' -f $groupName,$_.Exception.Message)}
            }
        }
    }
    $serviceAccounts=Invoke-LocalDiscoverySection 'Service Accounts' {
        $services | Where-Object {$_.StartName -and $_.StartName -notmatch '^(LocalSystem|LocalService|NetworkService|NT AUTHORITY\\|NT SERVICE\\)'} | ForEach-Object {
            New-LocalDiscoveryRow @{ComputerName=$ComputerName; Account=$_.StartName; Usage=('Windows service: {0}' -f $_.DisplayName); InteractiveLoginRequired='Unknown'; ManagedServiceAccount=$(if($_.StartName.EndsWith('$')){'Yes'}else{'No'})}
        }
    }
    $payload=New-LocalDiscoveryRow @{
        Metadata=(New-LocalDiscoveryRow @{ComputerName=$ComputerName; ServerClass=$class; CollectionMode='Local legacy basic only'; IsSqlServer=$isSql; IsExchangeServer=$isExchange; HasActiveDirectory=$hasAd; HasDns=$hasDns; HasDhcp=$hasDhcp; CollectedAt=Get-Date})
        System=@($system); Network=@($network); Storage=@($storage); RolesAndFeatures=@($roles)
        Applications=@($applications); Services=@($services); ListeningPorts=@($ports)
        SharesAndPermissions=@($shares); ScheduledTasks=@($tasks); LocalAccounts=@($accounts)
        LocalGroupMembership=@($membership); ServiceAccounts=@($serviceAccounts)
    }
    foreach($name in 'ActiveDirectory','ADUsers','ADGroupMembership','ADReplication','DHCPScopes','DHCPExclusions','DHCPReservations','DHCPOptions','DHCPFailover','DNSZones'){
        $payload | Add-Member NoteProperty $name @()
        $reason='Legacy local collection supports basic inventory only; role-specific details require the modern collector.'
        if($isSql -or $isExchange){$reason=$class+' detected; role-specific collectors are excluded.'}
        elseif(($name -like 'AD*' -or $name -eq 'ActiveDirectory') -and -not $hasAd){$reason='AD DS is not installed.'}
        elseif($name -like 'DHCP*' -and -not $hasDhcp){$reason='DHCP server is not installed.'}
        elseif($name -eq 'DNSZones' -and -not $hasDns){$reason='DNS server is not installed.'}
        Add-LocalDiscoveryDiagnostic $name Skipped $reason
    }
    $payload | Add-Member NoteProperty Diagnostics $script:LocalDiagnostics.ToArray()
    return $payload
}

function Convert-DiscoveryXmlText {
    param($Value)
    $text=[string]$Value
    # Escape SpreadsheetML's literal _xNNNN_ sequences as well as XML markup.
    $text=$text -replace '_x([0-9a-fA-F]{4})_', '_x005F_x$1_'
    $text=$text -replace '[\x00-\x08\x0B\x0C\x0E-\x1F]', ''
    [Security.SecurityElement]::Escape($text)
}

function Get-DiscoveryColumnName {
    param([int]$Number)
    $name=''
    while($Number -gt 0){$Number--; $name=[string][char](65+($Number%26))+$name; $Number=[int][math]::Floor($Number/26)}
    return $name
}

function Convert-DiscoveryCellXml {
    param([string]$Address,$Value,[int]$Style=0)
    if($null -eq $Value){return ('<c r="{0}" s="{1}"/>' -f $Address,$Style)}
    if($Value -is [datetime]){
        return ('<c r="{0}" s="2"><v>{1}</v></c>' -f $Address,$Value.ToOADate().ToString('R',[Globalization.CultureInfo]::InvariantCulture))
    }
    if($Value -is [bool]){$Value=if($Value){'Yes'}else{'No'}}
    elseif($Value -is [array]){$Value=Join-LocalDiscoveryValue $Value}
    elseif($Value -is [ValueType] -and -not($Value -is [enum]) -and -not($Value -is [timespan])){
        $numeric=0.0
        if([double]::TryParse([string]$Value,[ref]$numeric) -and -not [double]::IsNaN($numeric) -and -not [double]::IsInfinity($numeric)){
            return ('<c r="{0}" s="{1}"><v>{2}</v></c>' -f $Address,$Style,([IFormattable]$Value).ToString($null,[Globalization.CultureInfo]::InvariantCulture))
        }
    }
    $text=[string]$Value
    if($text.Length -gt 32767){
        $text=$text.Substring(0,32700)+' [truncated; full value in CLIXML snapshot]'
        Write-Warning ('Excel cell {0} exceeds 32,767 characters; the snapshot retains the full value.' -f $Address)
    }
    return ('<c r="{0}" s="{1}" t="inlineStr"><is><t xml:space="preserve">{2}</t></is></c>' -f $Address,$Style,(Convert-DiscoveryXmlText $text))
}

function Export-LocalDiscoveryWorkbook {
    param($Payload,[string]$Path)
    if(-not ('StandaloneDiscoveryZip' -as [type])){Add-Type -TypeDefinition $script:StandaloneZipSource -ErrorAction Stop}
    $metadata=$Payload.Metadata
    $failed=@($Payload.Diagnostics | Where-Object {$_.Status -eq 'Failed'})
    $warnings=@($Payload.Diagnostics | Where-Object {$_.Status -eq 'Warning'})
    $status=if($failed.Count){'Completed with collector failures'}elseif($warnings.Count){'Completed with warnings'}else{'Complete'}
    $summary=New-LocalDiscoveryRow @{
        ComputerName=$metadata.ComputerName; InventoryStatus=$status; ServerClass=$metadata.ServerClass
        CollectionMode=$metadata.CollectionMode; ExecutionMode='Local'; CollectedAt=$metadata.CollectedAt
        HasActiveDirectory=$metadata.HasActiveDirectory; HasDhcp=$metadata.HasDhcp; HasDns=$metadata.HasDns
        CollectorFailures=$failed.Count; Warnings=$warnings.Count
    }
    $sheets=@(New-LocalDiscoveryRow @{Name='Server Summary'; Rows=@($summary)})
    foreach($mapping in @(
        'System|System','Network|Network','Storage|Storage','Roles and Features|RolesAndFeatures',
        'Applications|Applications','Services|Services','Listening Ports|ListeningPorts',
        'Shares and Permissions|SharesAndPermissions','Scheduled Tasks|ScheduledTasks','Local Accounts|LocalAccounts',
        'Local Group Membership|LocalGroupMembership','Service Accounts|ServiceAccounts','Active Directory|ActiveDirectory',
        'AD Users|ADUsers','AD Group Membership|ADGroupMembership','AD Replication|ADReplication',
        'DHCP Scopes|DHCPScopes','DHCP Exclusions|DHCPExclusions','DHCP Reservations|DHCPReservations',
        'DHCP Options|DHCPOptions','DHCP Failover|DHCPFailover','DNS Zones|DNSZones','Diagnostics|Diagnostics'
    )){
        $pair=$mapping.Split('|'); $property=$Payload.PSObject.Properties[$pair[1]]; $rows=@()
        if($property){$rows=@($property.Value | Where-Object {$null -ne $_})}
        $sheets+=@(New-LocalDiscoveryRow @{Name=$pair[0]; Rows=$rows})
    }
    $parts=@{}
    $ns='http://schemas.openxmlformats.org/spreadsheetml/2006/main'
    $rels='http://schemas.openxmlformats.org/officeDocument/2006/relationships'
    $contentTypes='<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>'
    $workbook='<workbook xmlns="'+$ns+'" xmlns:r="'+$rels+'"><sheets>'
    $relationships='<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rIdStyles" Type="'+$rels+'/styles" Target="styles.xml"/>'
    for($index=0;$index -lt $sheets.Count;$index++){
        $sheet=$sheets[$index]; $number=$index+1; $rows=@($sheet.Rows)
        if(-not $rows.Count){$rows=@(New-LocalDiscoveryRow @{Status='No records returned. See Diagnostics for empty, skipped, or failed collectors.'})}
        if($rows.Count -gt 1048575){throw ('Sheet {0} exceeds the Excel row limit; the snapshot retains the inventory.' -f $sheet.Name)}
        $headers=New-Object 'System.Collections.Generic.List[string]'
        # Stable leading identity column, then every field seen in any row.
        if($rows[0].PSObject.Properties['ComputerName']){$headers.Add('ComputerName')}
        foreach($row in $rows){foreach($property in $row.PSObject.Properties){if(-not $headers.Contains($property.Name)){$headers.Add($property.Name)}}}
        if($headers.Count -gt 16384){throw 'Sheet exceeds the Excel column limit.'}
        $lastColumn=Get-DiscoveryColumnName $headers.Count; $lastRow=$rows.Count+1
        $xml=New-Object Text.StringBuilder
        [void]$xml.Append(('<worksheet xmlns="{0}"><dimension ref="A1:{1}{2}"/><sheetViews><sheetView workbookViewId="0" showGridLines="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><sheetFormatPr defaultRowHeight="30"/><cols><col min="1" max="{3}" width="26" customWidth="1"/></cols><sheetData><row r="1" ht="32" customHeight="1">' -f $ns,$lastColumn,$lastRow,$headers.Count))
        for($c=0;$c -lt $headers.Count;$c++){[void]$xml.Append((Convert-DiscoveryCellXml ((Get-DiscoveryColumnName ($c+1))+'1') $headers[$c] 1))}
        [void]$xml.Append('</row>')
        for($r=0;$r -lt $rows.Count;$r++){
            $lineCount=2
            foreach($p in $rows[$r].PSObject.Properties){
                $lines=0
                foreach($line in (([string]$p.Value) -split "`n")){$lines+=[int][math]::Max(1,[math]::Ceiling($line.Length/24.0))}
                $lineCount=[math]::Max($lineCount,$lines)
            }
            $height=[math]::Min(409,15*$lineCount)
            [void]$xml.Append(('<row r="{0}" ht="{1}" customHeight="1">' -f ($r+2),$height))
            for($c=0;$c -lt $headers.Count;$c++){
                $property=$rows[$r].PSObject.Properties[$headers[$c]]; $value=$null
                if($property){$value=$property.Value}
                $style=0
                if($headers[$c] -match 'Percent|Utilization|SizeGB|FreeGB|MemoryGB'){$style=3}
                [void]$xml.Append((Convert-DiscoveryCellXml ((Get-DiscoveryColumnName ($c+1))+($r+2)) $value $style))
            }
            [void]$xml.Append('</row>')
        }
        [void]$xml.Append(('</sheetData><autoFilter ref="A1:{0}{1}"/></worksheet>' -f $lastColumn,$lastRow))
        $parts['xl/worksheets/sheet'+$number+'.xml']=$xml.ToString()
        $workbook+='<sheet name="'+(Convert-DiscoveryXmlText $sheet.Name)+'" sheetId="'+$number+'" r:id="rId'+$number+'"/>'
        $relationships+='<Relationship Id="rId'+$number+'" Type="'+$rels+'/worksheet" Target="worksheets/sheet'+$number+'.xml"/>'
        $contentTypes+='<Override PartName="/xl/worksheets/sheet'+$number+'.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>'
    }
    $parts['xl/workbook.xml']=$workbook+'</sheets></workbook>'
    $parts['xl/_rels/workbook.xml.rels']=$relationships+'</Relationships>'
    $parts['[Content_Types].xml']=$contentTypes+'</Types>'
    $parts['_rels/.rels']='<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="'+$rels+'/officeDocument" Target="xl/workbook.xml"/></Relationships>'
    $parts['xl/styles.xml']='<styleSheet xmlns="'+$ns+'"><numFmts count="1"><numFmt numFmtId="164" formatCode="yyyy-mm-dd hh:mm:ss"/></numFmts><fonts count="2"><font><sz val="10"/><name val="Arial"/></font><font><b/><sz val="10"/><color rgb="FFFFFFFF"/><name val="Arial"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF1F4E79"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="4"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0" applyAlignment="1"><alignment vertical="top" wrapText="1"/></xf><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1" applyAlignment="1"><alignment vertical="center" wrapText="1"/></xf><xf numFmtId="164" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"/><xf numFmtId="2" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"/></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>'
    [StandaloneDiscoveryZip]::Write($Path,$parts)
}

$script:StandaloneModernSource=@'
#Requires -Version 4.0
<#
.SYNOPSIS
Collects discovery data from the Windows Server where this script executes.

.DESCRIPTION
This data-only collector is designed for local execution or Invoke-Command
-FilePath. It does not install modules or create files. SQL Server and Exchange
Server systems are automatically limited to basic inventory. AD DS, DHCP, and
DNS collectors run only when the matching role is installed and the server is
not classified as SQL or Exchange.
#>
[CmdletBinding()]
param(
    [bool]$IncludeMicrosoftTasks = $false
)

$ErrorActionPreference='Stop'
$ProgressPreference='SilentlyContinue'
$script:Diagnostics=New-Object 'System.Collections.Generic.List[object]'
$ComputerName=$env:COMPUTERNAME

function Add-DiscoveryDiagnostic {
    param(
        [string]$Collector,
        [ValidateSet('Success','Warning','Failed','Skipped')][string]$Status,
        [string]$Message,
        [int]$Count=0
    )
    $script:Diagnostics.Add([pscustomobject][ordered]@{
        Time=(Get-Date)
        ComputerName=$ComputerName
        Collector=$Collector
        Status=$Status
        RecordCount=$Count
        Message=$Message
    })
}

function Invoke-DiscoveryCollector {
    param([string]$Name,[scriptblock]$Action)
    try {
        $result=@(& $Action)
        Add-DiscoveryDiagnostic $Name Success 'Collector completed.' $result.Count
        Write-Output -NoEnumerate $result
    } catch {
        Add-DiscoveryDiagnostic $Name Failed $_.Exception.Message
        Write-Warning ('{0}: {1}' -f $Name,$_.Exception.Message)
        Write-Output -NoEnumerate @()
    }
}

function Join-DiscoveryValue {
    param([object[]]$Values,[string]$Separator='; ')
    $joined=(($Values | Where-Object {
        $null -ne $_ -and -not [string]::IsNullOrWhiteSpace([string]$_)
    } | ForEach-Object {
        ([string]$_).Trim()
    } | Sort-Object -Unique) -join $Separator)
    if([string]::IsNullOrWhiteSpace($joined)){return $null}
    return $joined
}

function Convert-PrefixToMask {
    param([ValidateRange(0,32)][int]$Prefix)
    $bits=(('1' * $Prefix) -join '').PadRight(32,'0')
    return ((0,8,16,24 | ForEach-Object {
        [Convert]::ToInt32($bits.Substring($_,8),2)
    }) -join '.')
}

if($env:OS -ne 'Windows_NT'){
    throw 'This collector must run on Windows.'
}

$system=Invoke-DiscoveryCollector 'System' {
    $cs=Get-CimInstance Win32_ComputerSystem
    $os=Get-CimInstance Win32_OperatingSystem
    $cpu=@(Get-CimInstance Win32_Processor)
    $bios=Get-CimInstance Win32_BIOS
    # HypervisorPresent is also true on physical Hyper-V hosts. Classify from
    # hardware vendor/model signatures so a Dell/HP host is not marked virtual.
    $virtual=(
        $cs.Manufacturer -match 'VMware|QEMU|Xen|innotek' -or
        $cs.Model -match 'Virtual Machine|VirtualBox|KVM|HVM domU|VMware|Bochs|Xen'
    )
    [pscustomobject][ordered]@{
        ComputerName=$cs.Name
        Domain=$cs.Domain
        Manufacturer=$cs.Manufacturer
        Model=$cs.Model
        SerialNumber=$bios.SerialNumber
        PhysicalOrVirtual=$(if($virtual){'Virtual'}else{'Physical'})
        OperatingSystem=$os.Caption
        Version=$os.Version
        Build=$os.BuildNumber
        LastBoot=$os.LastBootUpTime
        CPU=(Join-DiscoveryValue $cpu.Name)
        Sockets=$cpu.Count
        Cores=($cpu | Measure-Object NumberOfCores -Sum).Sum
        LogicalProcessors=($cpu | Measure-Object NumberOfLogicalProcessors -Sum).Sum
        MemoryGB=[math]::Round($cs.TotalPhysicalMemory/1GB,2)
    }
}

$network=Invoke-DiscoveryCollector 'Network' {
    foreach($config in Get-NetIPConfiguration | Where-Object {$_.NetAdapter.Status -eq 'Up'}){
        foreach($ip in @($config.IPv4Address)){
            [pscustomobject][ordered]@{
                ComputerName=$ComputerName
                Interface=$config.InterfaceAlias
                IPAddress=$ip.IPAddress
                PrefixLength=$ip.PrefixLength
                SubnetMask=(Convert-PrefixToMask $ip.PrefixLength)
                Gateway=(Join-DiscoveryValue $config.IPv4DefaultGateway.NextHop)
                DNS=(Join-DiscoveryValue @($config.DNSServer.ServerAddresses | Where-Object {
                    ($_ -as [ipaddress]) -and
                    ([ipaddress]$_).AddressFamily -eq [Net.Sockets.AddressFamily]::InterNetwork
                }))
                MacAddress=$config.NetAdapter.MacAddress
            }
        }
    }
}

$storage=Invoke-DiscoveryCollector 'Storage' {
    Get-CimInstance Win32_LogicalDisk -Filter 'DriveType=3' |
      Sort-Object DeviceID | ForEach-Object {
        [pscustomobject][ordered]@{
            ComputerName=$ComputerName
            Drive=$_.DeviceID
            Label=$_.VolumeName
            FileSystem=$_.FileSystem
            SizeGB=[math]::Round($_.Size/1GB,2)
            FreeGB=[math]::Round($_.FreeSpace/1GB,2)
            PercentFree=$(if($_.Size){[math]::Round(100*$_.FreeSpace/$_.Size,2)}else{$null})
        }
      }
}

$rolesAndFeatures=Invoke-DiscoveryCollector 'Roles and Features' {
    if(-not(Get-Command Get-WindowsFeature -ErrorAction SilentlyContinue)){
        throw 'Get-WindowsFeature is unavailable.'
    }
    Get-WindowsFeature | Where-Object Installed | ForEach-Object {
        [pscustomobject][ordered]@{
            ComputerName=$ComputerName
            Name=$_.Name
            DisplayName=$_.DisplayName
            FeatureType=$_.FeatureType
        }
    }
}

$applications=Invoke-DiscoveryCollector 'Applications' {
    $paths=@(
        'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*',
        'HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*'
    )
    Get-ItemProperty $paths -ErrorAction SilentlyContinue |
      Where-Object {$_.DisplayName -and $_.SystemComponent -ne 1} |
      Sort-Object DisplayName,DisplayVersion -Unique | ForEach-Object {
        [pscustomobject][ordered]@{
            ComputerName=$ComputerName
            Name=$_.DisplayName
            Version=$_.DisplayVersion
            Publisher=$_.Publisher
            InstallDate=$_.InstallDate
            InstallLocation=$_.InstallLocation
        }
      }
}

$services=Invoke-DiscoveryCollector 'Services' {
    Get-CimInstance Win32_Service | Sort-Object DisplayName | ForEach-Object {
        [pscustomobject][ordered]@{
            ComputerName=$ComputerName
            Name=$_.Name
            DisplayName=$_.DisplayName
            State=$_.State
            StartMode=$_.StartMode
            StartName=$_.StartName
            PathName=$_.PathName
        }
    }
}

$isSqlServer=@($services | Where-Object {
    $_.Name -match '^(MSSQLSERVER|MSSQL\$|SQLSERVERAGENT|SQLAgent\$|MSOLAP\$|MSSQLServerOLAPService|ReportServer|ReportServer\$)'
}).Count -gt 0
$isExchangeServer=@($services | Where-Object {$_.Name -match '^MSExchange'}).Count -gt 0
$serverClass=if($isSqlServer -and $isExchangeServer){
    'SQL and Exchange'
}elseif($isSqlServer){
    'SQL Server'
}elseif($isExchangeServer){
    'Exchange Server'
}else{
    'General Server'
}
$basicOnly=$isSqlServer -or $isExchangeServer
$collectionMode=if($basicOnly){'Basic only'}else{'Full role-aware'}

foreach($row in $system){
    $row | Add-Member NoteProperty ServerClass $serverClass -Force
    $row | Add-Member NoteProperty CollectionMode $collectionMode -Force
}

$listeningPorts=Invoke-DiscoveryCollector 'Listening Ports' {
    Get-NetTCPConnection -State Listen |
      Sort-Object LocalPort,LocalAddress -Unique | ForEach-Object {
        [pscustomobject][ordered]@{
            ComputerName=$ComputerName
            LocalAddress=$_.LocalAddress
            LocalPort=$_.LocalPort
            ProcessId=$_.OwningProcess
            ProcessName=$(try{
                (Get-Process -Id $_.OwningProcess -ErrorAction Stop).ProcessName
            }catch{$null})
        }
      }
}

$shares=Invoke-DiscoveryCollector 'Shares and Permissions' {
    if(-not(Get-Command Get-SmbShare -ErrorAction SilentlyContinue)){
        throw 'Get-SmbShare is unavailable.'
    }
    Get-SmbShare | Sort-Object Name | ForEach-Object {
        $share=$_
        $shareAcl=try{
            Get-SmbShareAccess $share.Name | ForEach-Object {
                '{0}: {1} ({2})' -f $_.AccountName,$_.AccessRight,$_.AccessControlType
            }
        }catch{@()}
        $ntfsAcl=try{
            if($share.Path -and (Test-Path -LiteralPath $share.Path)){
                (Get-Acl -LiteralPath $share.Path).Access | ForEach-Object {
                    '{0}: {1} ({2})' -f $_.IdentityReference,$_.FileSystemRights,$_.AccessControlType
                }
            }
        }catch{@()}
        [pscustomobject][ordered]@{
            ComputerName=$ComputerName
            Name=$share.Name
            Path=$share.Path
            UNCPath=('\\{0}\{1}' -f $ComputerName,$share.Name)
            Description=$share.Description
            Special=$share.Special
            SharePermissions=(Join-DiscoveryValue $shareAcl)
            NTFSPermissions=(Join-DiscoveryValue $ntfsAcl)
        }
    }
}

$scheduledTasks=Invoke-DiscoveryCollector 'Scheduled Tasks' {
    if(-not(Get-Command Get-ScheduledTask -ErrorAction SilentlyContinue)){
        throw 'Get-ScheduledTask is unavailable.'
    }
    Get-ScheduledTask | Where-Object {
        $IncludeMicrosoftTasks -or $_.TaskPath -notlike '\Microsoft\*'
    } | Sort-Object TaskPath,TaskName | ForEach-Object {
        [pscustomobject][ordered]@{
            ComputerName=$ComputerName
            Name=$_.TaskName
            TaskPath=$_.TaskPath
            Executable=(Join-DiscoveryValue ($_.Actions | ForEach-Object {
                ('{0} {1}' -f $_.Execute,$_.Arguments).Trim()
            }))
            State=$_.State
            RunAsUser=$_.Principal.UserId
            Description=$_.Description
        }
    }
}

$localAccounts=Invoke-DiscoveryCollector 'Local Accounts' {
    if($rolesAndFeatures.Name -contains 'AD-Domain-Services'){return}
    if(Get-Command Get-LocalUser -ErrorAction SilentlyContinue){
        Get-LocalUser | Sort-Object Name | Select-Object @{n='ComputerName';e={$ComputerName}},Name,Enabled,Description,LastLogon,PasswordExpires
        return
    }
    Add-DiscoveryDiagnostic 'Local Accounts Compatibility' Warning 'Get-LocalUser is unavailable; using Win32_UserAccount.'
    Get-CimInstance Win32_UserAccount -Filter 'LocalAccount=True' | Sort-Object Name | ForEach-Object {
        [pscustomobject][ordered]@{
            ComputerName=$ComputerName
            Name=$_.Name
            Enabled=(-not $_.Disabled)
            Description=$_.Description
            LastLogon=$null
            PasswordExpires=$_.PasswordExpires
        }
    }
}

$localGroupMembership=Invoke-DiscoveryCollector 'Local Group Membership' {
    if($rolesAndFeatures.Name -contains 'AD-Domain-Services'){return}
    if(Get-Command Get-LocalGroupMember -ErrorAction SilentlyContinue){
        foreach($group in Get-LocalGroup){
            try{
                Get-LocalGroupMember $group.Name -ErrorAction Stop | Select-Object @{n='ComputerName';e={$ComputerName}},@{n='Group';e={$group.Name}},Name,ObjectClass,PrincipalSource
            }catch{
                Add-DiscoveryDiagnostic 'Local Group Membership' Warning ('{0}: {1}' -f $group.Name,$_.Exception.Message)
            }
        }
        return
    }
    Add-DiscoveryDiagnostic 'Local Group Membership Compatibility' Warning 'Local group cmdlets are unavailable; using the WinNT provider.'
    $computer=[ADSI]('WinNT://{0},computer' -f $ComputerName)
    foreach($group in @($computer.psbase.Children | Where-Object {$_.SchemaClassName -eq 'group'})){
        $groupName=[string]$group.Name
        foreach($member in @($group.psbase.Invoke('Members'))){
            try{
                $memberType=$member.GetType()
                $memberName=$memberType.InvokeMember('Name','GetProperty',$null,$member,$null)
                $memberClass=$memberType.InvokeMember('Class','GetProperty',$null,$member,$null)
                $adsPath=$memberType.InvokeMember('AdsPath','GetProperty',$null,$member,$null)
                [pscustomobject][ordered]@{
                    ComputerName=$ComputerName
                    Group=$groupName
                    Name=$(if($adsPath){$adsPath -replace '^WinNT://','' -replace '/','\\'}else{$memberName})
                    ObjectClass=$memberClass
                    PrincipalSource='WinNT'
                }
            }catch{
                Add-DiscoveryDiagnostic 'Local Group Membership' Warning ('{0}: {1}' -f $groupName,$_.Exception.Message)
            }
        }
    }
}

$serviceAccounts=@(
    $services | Where-Object {
        $_.StartName -and
        $_.StartName -notmatch '^(LocalSystem|LocalService|NetworkService|NT AUTHORITY\\|NT SERVICE\\)'
    } | ForEach-Object {
        [pscustomobject][ordered]@{
            ComputerName=$ComputerName
            Account=$_.StartName
            Usage=('Windows service: {0}' -f $_.DisplayName)
            InteractiveLoginRequired='Unknown'
            ManagedServiceAccount=$(if($_.StartName.EndsWith('$')){'Yes'}else{'No'})
        }
    } | Sort-Object Account,Usage -Unique
)
Add-DiscoveryDiagnostic 'Service Accounts' Success 'Collector completed.' $serviceAccounts.Count

$activeDirectory=@()
$adUsers=@()
$adGroupMembership=@()
$adReplication=@()
$dhcpScopes=@()
$dhcpExclusions=@()
$dhcpReservations=@()
$dhcpOptions=@()
$dhcpFailover=@()
$dnsZones=@()

if($basicOnly){
    $reason=('{0} detected; role-specific AD, DHCP, and DNS collectors were skipped.' -f $serverClass)
    foreach($collectorName in 'Active Directory','AD Users','AD Group Membership','AD Replication','DHCP Scopes','DHCP Exclusions','DHCP Reservations','DHCP Options','DHCP Failover','DNS Zones'){
        Add-DiscoveryDiagnostic $collectorName Skipped $reason
    }
}else{
    if($rolesAndFeatures.Name -contains 'AD-Domain-Services'){
        $activeDirectory=Invoke-DiscoveryCollector 'Active Directory' {
            if(-not(Get-Module -ListAvailable ActiveDirectory)){
                throw 'ActiveDirectory module is unavailable.'
            }
            Import-Module ActiveDirectory -ErrorAction Stop
            $dc=Get-ADDomainController -Identity $ComputerName
            $domain=Get-ADDomain
            $forest=Get-ADForest
            [pscustomobject][ordered]@{
                ComputerName=$ComputerName
                FQDN=$dc.HostName
                Site=$dc.Site
                IPv4=$dc.IPv4Address
                OperatingSystem=$dc.OperatingSystem
                GlobalCatalog=$dc.IsGlobalCatalog
                ReadOnly=$dc.IsReadOnly
                DomainFQDN=$domain.DNSRoot
                DomainShortName=$domain.NetBIOSName
                UPNSuffixes=(Join-DiscoveryValue @($forest.UPNSuffixes))
                DomainMode=[string]$domain.DomainMode
                ForestMode=[string]$forest.ForestMode
                PDC=$domain.PDCEmulator
                RIDMaster=$domain.RIDMaster
                InfrastructureMaster=$domain.InfrastructureMaster
                SchemaMaster=$forest.SchemaMaster
                NamingMaster=$forest.DomainNamingMaster
            }
        }

        $adUsers=Invoke-DiscoveryCollector 'AD Users' {
            Import-Module ActiveDirectory -ErrorAction Stop
            $domain=(Get-ADDomain).DNSRoot
            $userProperties='GivenName','Surname','DisplayName','UserPrincipalName','StreetAddress','City','State','PostalCode','co','Title','Department','Company','Manager','Description','Office','OfficePhone','EmailAddress','MobilePhone','Info','Enabled','LastLogonDate','ServicePrincipalName','PasswordNeverExpires','DistinguishedName'
            Get-ADUser -Filter * -Properties $userProperties |
              Sort-Object SamAccountName | ForEach-Object {
                [pscustomobject][ordered]@{
                    Domain=$domain
                    CollectedFrom=$ComputerName
                    DistinguishedName=$_.DistinguishedName
                    FirstName=$_.GivenName
                    LastName=$_.Surname
                    DisplayName=$_.DisplayName
                    SamAccountName=$_.SamAccountName
                    UserPrincipalName=$_.UserPrincipalName
                    Street=$_.StreetAddress
                    City=$_.City
                    State=$_.State
                    PostalCode=$_.PostalCode
                    Country=$_.co
                    JobTitle=$_.Title
                    Department=$_.Department
                    Company=$_.Company
                    Manager=$_.Manager
                    Description=$_.Description
                    Office=$_.Office
                    Telephone=$_.OfficePhone
                    Email=$_.EmailAddress
                    Mobile=$_.MobilePhone
                    Notes=$_.Info
                    Enabled=$_.Enabled
                    LastLogonDate=$_.LastLogonDate
                    LikelyServiceAccount=$(
                        $_.SamAccountName.EndsWith('$') -or
                        @($_.ServicePrincipalName).Count -gt 0
                    )
                    PasswordNeverExpires=$_.PasswordNeverExpires
                }
              }
        }

        $adGroupMembership=Invoke-DiscoveryCollector 'AD Group Membership' {
            Import-Module ActiveDirectory -ErrorAction Stop
            $domain=Get-ADDomain
            $primaryGroups=@{}
            foreach($user in Get-ADUser -Filter * -Properties DisplayName,MemberOf,PrimaryGroupID){
                foreach($groupDn in @($user.MemberOf)){
                    $groupName=(($groupDn -split '(?<!\\),')[0] -replace '^CN=','') -replace '\\,',','
                    [pscustomobject][ordered]@{
                        Domain=$domain.DNSRoot
                        CollectedFrom=$ComputerName
                        Username=$user.SamAccountName
                        Name=$user.DisplayName
                        GroupName=$groupName
                        MembershipType='Direct'
                    }
                }
                $rid=[string]$user.PrimaryGroupID
                if($rid){
                    if(-not $primaryGroups.ContainsKey($rid)){
                        $primarySid='{0}-{1}' -f $domain.DomainSID.Value,$rid
                        $primaryGroups[$rid]=(Get-ADGroup -Identity $primarySid).Name
                    }
                    [pscustomobject][ordered]@{
                        Domain=$domain.DNSRoot
                        CollectedFrom=$ComputerName
                        Username=$user.SamAccountName
                        Name=$user.DisplayName
                        GroupName=$primaryGroups[$rid]
                        MembershipType='Primary'
                    }
                }
            }
        }

        $adReplication=Invoke-DiscoveryCollector 'AD Replication' {
            Import-Module ActiveDirectory -ErrorAction Stop
            Get-ADReplicationPartnerMetadata -Target $ComputerName -Scope Server |
              ForEach-Object {
                [pscustomobject][ordered]@{
                    ComputerName=$ComputerName
                    FromServer=$_.Partner
                    ToServer=$_.Server
                    LastSync=$_.LastReplicationSuccess
                    Status=$(if($_.LastReplicationResult -eq 0){
                        'Success'
                    }else{
                        'Error {0}' -f $_.LastReplicationResult
                    })
                }
              }
        }
    }else{
        foreach($collectorName in 'Active Directory','AD Users','AD Group Membership','AD Replication'){
            Add-DiscoveryDiagnostic $collectorName Skipped 'AD DS role is not installed.'
        }
    }

    if($rolesAndFeatures.Name -contains 'DHCP'){
        $dhcpScopes=Invoke-DiscoveryCollector 'DHCP Scopes' {
            if(-not(Get-Command Get-DhcpServerv4Scope -ErrorAction SilentlyContinue)){
                throw 'DHCP cmdlets are unavailable.'
            }
            foreach($scope in Get-DhcpServerv4Scope -ComputerName $ComputerName -ErrorAction Stop){
                $stats=try{
                    Get-DhcpServerv4ScopeStatistics -ComputerName $ComputerName -ScopeId $scope.ScopeId -ErrorAction Stop
                }catch{
                    Add-DiscoveryDiagnostic 'DHCP Scope Statistics' Warning ('{0}: {1}' -f $scope.ScopeId,$_.Exception.Message)
                    $null
                }
                [pscustomobject][ordered]@{
                    ServerName=$ComputerName
                    ScopeName=$scope.Name
                    Status=$scope.State
                    ScopeId=$scope.ScopeId
                    StartRange=$scope.StartRange
                    EndRange=$scope.EndRange
                    SubnetMask=$scope.SubnetMask
                    AddressPool=('{0} - {1}' -f $scope.StartRange,$scope.EndRange)
                    LeaseDuration=$scope.LeaseDuration
                    Utilization=$(if($stats){$stats.PercentageInUse}else{$null})
                    NAP=$(if($scope.PSObject.Properties['NapEnable']){$scope.NapEnable}else{$null})
                }
            }
        }

        $dhcpExclusions=Invoke-DiscoveryCollector 'DHCP Exclusions' {
            foreach($scope in $dhcpScopes){
                Get-DhcpServerv4ExclusionRange -ComputerName $ComputerName -ScopeId $scope.ScopeId -ErrorAction Stop | ForEach-Object {
                    [pscustomobject][ordered]@{
                        ServerName=$ComputerName
                        ScopeId=$scope.ScopeId
                        ScopeName=$scope.ScopeName
                        StartRange=$_.StartRange
                        EndRange=$_.EndRange
                    }
                  }
            }
        }

        $dhcpReservations=Invoke-DiscoveryCollector 'DHCP Reservations' {
            foreach($scope in $dhcpScopes){
                Get-DhcpServerv4Reservation -ComputerName $ComputerName -ScopeId $scope.ScopeId -ErrorAction Stop | ForEach-Object {
                    [pscustomobject][ordered]@{
                        ServerName=$ComputerName
                        ScopeId=$scope.ScopeId
                        ScopeName=$scope.ScopeName
                        IPAddress=$_.IPAddress
                        ClientId=$_.ClientId
                        Name=$_.Name
                        Description=$_.Description
                        Type=$_.Type
                    }
                  }
            }
        }

        $dhcpOptions=Invoke-DiscoveryCollector 'DHCP Options' {
            foreach($scope in $dhcpScopes){
                Get-DhcpServerv4OptionValue -ComputerName $ComputerName -ScopeId $scope.ScopeId -ErrorAction Stop | ForEach-Object {
                    [pscustomobject][ordered]@{
                        ServerName=$ComputerName
                        ScopeId=$scope.ScopeId
                        ScopeName=$scope.ScopeName
                        OptionId=$_.OptionId
                        Name=$_.Name
                        Type=$_.Type
                        Value=(Join-DiscoveryValue @($_.Value) ', ')
                        VendorClass=$_.VendorClass
                        UserClass=$_.UserClass
                        PolicyName=$_.PolicyName
                    }
                  }
            }
        }

        $dhcpFailover=Invoke-DiscoveryCollector 'DHCP Failover' {
            Get-DhcpServerv4Failover -ComputerName $ComputerName -ErrorAction SilentlyContinue | ForEach-Object {
                [pscustomobject][ordered]@{
                    ServerName=$ComputerName
                    Name=$_.Name
                    PartnerServer=$_.PartnerServer
                    Mode=$_.Mode
                    State=$_.State
                    ServerRole=$_.ServerRole
                    ScopeId=(Join-DiscoveryValue @($_.ScopeId))
                    LoadBalancePercent=$_.LoadBalancePercent
                    ReservePercent=$_.ReservePercent
                    MaxClientLeadTime=$_.MaxClientLeadTime
                    AutoStateTransition=$_.AutoStateTransition
                    StateSwitchInterval=$_.StateSwitchInterval
                }
              }
        }
    }else{
        foreach($collectorName in 'DHCP Scopes','DHCP Exclusions','DHCP Reservations','DHCP Options','DHCP Failover'){
            Add-DiscoveryDiagnostic $collectorName Skipped 'DHCP role is not installed.'
        }
    }

    if($rolesAndFeatures.Name -contains 'DNS'){
        $dnsZones=Invoke-DiscoveryCollector 'DNS Zones' {
            if(-not(Get-Command Get-DnsServerZone -ErrorAction SilentlyContinue)){
                throw 'DNS cmdlets are unavailable.'
            }
            Get-DnsServerZone -ComputerName $ComputerName -ErrorAction Stop |
              Sort-Object ZoneName | Select-Object @{n='ComputerName';e={$ComputerName}},ZoneName,ZoneType,IsReverseLookupZone,IsDsIntegrated,DynamicUpdate,ReplicationScope
        }
    }else{
        Add-DiscoveryDiagnostic 'DNS Zones' Skipped 'DNS role is not installed.'
    }
}

[pscustomobject][ordered]@{
    Metadata=[pscustomobject][ordered]@{
        ComputerName=$ComputerName
        ServerClass=$serverClass
        CollectionMode=$collectionMode
        IsSqlServer=$isSqlServer
        IsExchangeServer=$isExchangeServer
        HasActiveDirectory=($rolesAndFeatures.Name -contains 'AD-Domain-Services')
        HasDhcp=($rolesAndFeatures.Name -contains 'DHCP')
        HasDns=($rolesAndFeatures.Name -contains 'DNS')
        CollectedAt=(Get-Date)
    }
    System=@($system)
    Network=@($network)
    Storage=@($storage)
    RolesAndFeatures=@($rolesAndFeatures)
    Applications=@($applications)
    Services=@($services)
    ListeningPorts=@($listeningPorts)
    SharesAndPermissions=@($shares)
    ScheduledTasks=@($scheduledTasks)
    LocalAccounts=@($localAccounts)
    LocalGroupMembership=@($localGroupMembership)
    ServiceAccounts=@($serviceAccounts)
    ActiveDirectory=@($activeDirectory)
    ADUsers=@($adUsers)
    ADGroupMembership=@($adGroupMembership)
    ADReplication=@($adReplication)
    DHCPScopes=@($dhcpScopes)
    DHCPExclusions=@($dhcpExclusions)
    DHCPReservations=@($dhcpReservations)
    DHCPOptions=@($dhcpOptions)
    DHCPFailover=@($dhcpFailover)
    DNSZones=@($dnsZones)
    # New-Object keeps this collector compatible with PowerShell 4.0. Use
    # ToArray(): @($list) can throw on its wrapped List[object] in PowerShell 5+.
    Diagnostics=$script:Diagnostics.ToArray()
}
'@

$script:StandaloneZipSource=@'
// Small ZIP container writer for .NET 2.0+. No external assemblies or binaries.
using System;
using System.IO;
using System.IO.Compression;
using System.Text;
using System.Collections;
using System.Collections.Generic;

public static class StandaloneDiscoveryZip {
    private sealed class Entry {
        public byte[] Name;
        public uint Crc, Size, CompressedSize, Offset;
    }
    private static uint Crc32(byte[] data) {
        uint[] table = new uint[256];
        for (uint i = 0; i < 256; i++) {
            uint c = i;
            for (int bit = 0; bit < 8; bit++) c = (c & 1) != 0 ? 0xedb88320U ^ (c >> 1) : c >> 1;
            table[i] = c;
        }
        uint crc = 0xffffffffU;
        foreach (byte value in data) crc = table[(crc ^ value) & 255] ^ (crc >> 8);
        return crc ^ 0xffffffffU;
    }
    public static void Write(string path, IDictionary parts) {
        if (parts.Count > 65535) throw new InvalidOperationException("Too many XLSX parts.");
        List<Entry> entries = new List<Entry>();
        using (BinaryWriter writer = new BinaryWriter(new FileStream(path, FileMode.CreateNew))) {
            foreach (DictionaryEntry item in parts) {
                byte[] data = new UTF8Encoding(false).GetBytes((string)item.Value);
                byte[] packed;
                using (MemoryStream buffer = new MemoryStream()) {
                    using (DeflateStream deflater = new DeflateStream(buffer, CompressionMode.Compress)) {
                        deflater.Write(data, 0, data.Length);
                    }
                    packed = buffer.ToArray();
                }
                if (writer.BaseStream.Position + packed.Length + 1024 > UInt32.MaxValue)
                    throw new InvalidOperationException("Workbook exceeds the ZIP32 limit; the CLIXML snapshot retains the inventory.");
                Entry entry = new Entry();
                entry.Name = Encoding.UTF8.GetBytes((string)item.Key);
                entry.Crc = Crc32(data); entry.Size = (uint)data.Length;
                entry.CompressedSize = (uint)packed.Length; entry.Offset = (uint)writer.BaseStream.Position;
                writer.Write(0x04034b50U); writer.Write((ushort)20); writer.Write((ushort)0x800);
                writer.Write((ushort)8); writer.Write((ushort)0); writer.Write((ushort)0x2821);
                writer.Write(entry.Crc); writer.Write(entry.CompressedSize); writer.Write(entry.Size);
                writer.Write((ushort)entry.Name.Length); writer.Write((ushort)0); writer.Write(entry.Name); writer.Write(packed);
                entries.Add(entry);
            }
            uint start = (uint)writer.BaseStream.Position;
            foreach (Entry entry in entries) {
                writer.Write(0x02014b50U); writer.Write((ushort)20); writer.Write((ushort)20);
                writer.Write((ushort)0x800); writer.Write((ushort)8); writer.Write((ushort)0); writer.Write((ushort)0x2821);
                writer.Write(entry.Crc); writer.Write(entry.CompressedSize); writer.Write(entry.Size);
                writer.Write((ushort)entry.Name.Length); writer.Write((ushort)0); writer.Write((ushort)0);
                writer.Write((ushort)0); writer.Write((ushort)0); writer.Write(0U); writer.Write(entry.Offset); writer.Write(entry.Name);
            }
            uint size = (uint)writer.BaseStream.Position - start;
            writer.Write(0x06054b50U); writer.Write((ushort)0); writer.Write((ushort)0);
            writer.Write((ushort)entries.Count); writer.Write((ushort)entries.Count);
            writer.Write(size); writer.Write(start); writer.Write((ushort)0);
        }
    }
}
'@

function Test-StandaloneModernCollector {
    param([version]$PowerShellVersion,[version]$WindowsVersion,[bool]$ForceLegacy=$false)
    return (-not $ForceLegacy -and $PowerShellVersion.Major -ge 4 -and $WindowsVersion -ge [version]'6.2')
}

function Invoke-StandaloneDiscovery {
    param([string]$OutputDirectory='C:\Temp',[bool]$IncludeMicrosoftTasks=$false,[bool]$UseLegacyCollector=$false)
    $ErrorActionPreference='Stop'
    if($env:OS -ne 'Windows_NT'){throw 'Run this script directly on the Windows Server being inventoried.'}
    $identity=[Security.Principal.WindowsIdentity]::GetCurrent()
    $principal=New-Object Security.Principal.WindowsPrincipal -ArgumentList $identity
    if(-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)){
        throw 'Open Windows PowerShell using Run as administrator under an administrator account for this server, then run this script again.'
    }
    if(-not(Test-Path -LiteralPath $OutputDirectory)){New-Item -ItemType Directory -Path $OutputDirectory -Force | Out-Null}
    $OutputDirectory=(Resolve-Path -LiteralPath $OutputDirectory).ProviderPath
    $version=$PSVersionTable.PSVersion
    $osVersion=[Environment]::OSVersion.Version
    $useModern=Test-StandaloneModernCollector $version $osVersion $UseLegacyCollector
    Write-Host ('Discovering {0} locally as {1} (PowerShell {2})...' -f $env:COMPUTERNAME,$identity.Name,$version)
    $primaryError=$null
    if($useModern){
        try{
            # The embedded collector is parsed only on a compatible runtime.
            $payload=& ([scriptblock]::Create($script:StandaloneModernSource)) $IncludeMicrosoftTasks
            if(-not $payload -or -not $payload.PSObject.Properties['Metadata']){throw 'Modern collector did not return an inventory payload.'}
        }catch{
            $primaryError=$_.Exception.Message
            Write-Warning ('Modern local collector failed: {0}. Trying local basic inventory.' -f $primaryError)
            $useModern=$false
        }
    }
    if(-not $useModern){$payload=Get-LocalBasicDiscoveryData -IncludeMicrosoftTasks $IncludeMicrosoftTasks}
    if($primaryError){
        $payload.Diagnostics=@($payload.Diagnostics)+@(New-LocalDiscoveryRow @{Time=Get-Date; ComputerName=$env:COMPUTERNAME; Collector='Modern Local Collection'; Status='Warning'; RecordCount=0; Message=$primaryError})
    }
    $payload.Metadata | Add-Member NoteProperty ExecutionMode 'Local' -Force
    $payload.Metadata | Add-Member NoteProperty RunAs $identity.Name -Force
    $payload.Metadata | Add-Member NoteProperty PowerShellVersion ([string]$version) -Force
    if($env:PROCESSOR_ARCHITEW6432){
        $payload.Diagnostics=@($payload.Diagnostics)+@(New-LocalDiscoveryRow @{Time=Get-Date; ComputerName=$env:COMPUTERNAME; Collector='Process Architecture'; Status='Warning'; RecordCount=0; Message='32-bit PowerShell on a 64-bit OS may omit 64-bit software. Rerun from 64-bit Windows PowerShell for a complete application list.'})
    }
    $prefix=('{0}-ServerDiscovery-{1}' -f $env:COMPUTERNAME,(Get-Date -Format 'yyyyMMdd-HHmmss-fff'))
    $snapshotPath=Join-Path $OutputDirectory ($prefix+'.clixml')
    $outputPath=Join-Path $OutputDirectory ($prefix+'.xlsx')
    # Preserve all collected data before rendering Excel (including long cells).
    $payload | Export-Clixml -Path $snapshotPath -Depth 12 -Encoding UTF8 -NoClobber
    try{Export-LocalDiscoveryWorkbook -Payload $payload -Path $outputPath}
    catch{throw ('Excel export failed: {0}. Collected inventory is retained at {1}' -f $_.Exception.Message,$snapshotPath)}
    $failed=@($payload.Diagnostics | Where-Object {$_.Status -eq 'Failed'}).Count
    Write-Host ('Local discovery completed. Collector failures: {0}' -f $failed)
    Write-Host ('Output: {0}' -f $outputPath)
    Write-Host ('Inventory snapshot: {0}' -f $snapshotPath)
    Write-Output $outputPath
}

if($MyInvocation.InvocationName -ne '.'){
    Invoke-StandaloneDiscovery -OutputDirectory $OutputDirectory -IncludeMicrosoftTasks ([bool]$IncludeMicrosoftTasks) -UseLegacyCollector ([bool]$UseLegacyCollector)
}
