#Requires -Version 2.0
<#
.SYNOPSIS
Inventories this Windows Server locally and writes an XLSX workbook to C:\Temp.
.DESCRIPTION
Run elevated under the local or domain administrator account for this server.
This self-contained file does not enumerate AD computers, use WinRM, install
modules, or connect to GitHub. Windows PowerShell 2.0 and later are supported
by the legacy basic collector; the modern collector requires PowerShell 4.0
and Windows Server 2012 or later. Unsupported sections are diagnosed.
.EXAMPLE
.\Invoke-StandaloneServerDiscovery.ps1
.EXAMPLE
.\Invoke-StandaloneServerDiscovery.ps1 -OutputDirectory D:\Discovery
#>
[CmdletBinding()]
param(
    [string]$OutputDirectory='C:\Temp',
    [switch]$IncludeMicrosoftTasks,
    [switch]$UseLegacyCollector
)

# Generated by Standalone/Build-StandaloneServerDiscovery.ps1. Edit its sources.

function New-LocalDiscoveryRow {
    param([hashtable]$Values)
    New-Object PSObject -Property $Values
}

function Add-LocalDiscoveryDiagnostic {
    param([string]$Collector,[string]$Status,[string]$Message,[int]$Count=0)
    $script:LocalDiagnostics.Add((New-LocalDiscoveryRow @{
        Time=Get-Date; ComputerName=$env:COMPUTERNAME; Collector=$Collector
        Status=$Status; RecordCount=$Count; Message=$Message
    }))
}

function Invoke-LocalDiscoverySection {
    param([string]$Name,[scriptblock]$Action)
    Write-Host ('Collecting {0}...' -f $Name)
    # Retain rows already received if a later record in the section fails.
    $records=New-Object 'System.Collections.Generic.List[object]'
    try {
        & $Action | ForEach-Object {if($null -ne $_){$records.Add($_)}}
        Add-LocalDiscoveryDiagnostic $Name Success 'Local collector completed.' $records.Count
    } catch {
        Add-LocalDiscoveryDiagnostic $Name Failed $_.Exception.Message $records.Count
        Write-Warning ('{0}: {1}' -f $Name,$_.Exception.Message)
    }
    Write-Output -NoEnumerate $records.ToArray()
}

function Join-LocalDiscoveryValue {
    param([object[]]$Values,[string]$Separator='; ')
    (@($Values | Where-Object {$null -ne $_ -and ([string]$_).Trim()} |
        ForEach-Object {([string]$_).Trim()} | Sort-Object -Unique) -join $Separator)
}

function Convert-LocalDiscoveryDate {
    param($Value)
    if($Value -is [datetime]){return $Value}
    if($Value){try{[Management.ManagementDateTimeConverter]::ToDateTime([string]$Value)}catch{$null}}
}
